### ISSUE TITLE
fix movement / new input system

### ISSUE THREAD

**Issue by PimMiii** [SillyBusinessInc/Moldbreaker#91]
~~Add movement to FixedUpdate or add deltatime into the update, so movement can be more consistent.~~
TIL: Forcemode.Acceleration already is fixed time : https://docs.unity3d.com/ScriptReference/ForceMode.Acceleration.html 
So adding it into FixedUpdate or adding a * Time.deltaTime 'broke' it, as it was multiplying by the deltaTime/physics step twice.

**Comment by SuaveGiant** [comment]
-Character should return to the ground when jumping sooner (increase gravity)
-Dodge cooldown does nothing. Dodge is extremely spammable to reach insane speeds.
-Sometimes the character speeds up? I have no clue what causes this. By default (10 movement speed) he is extremely slow, as if dragging his fat balls over the floor.
